atualizações do teste
não consegui testar atraves do controlador_sistema, o teste da erro logo no inicio:  ImportError: cannot import name 'ControladorSistema' from partially initialized module 'controlador_sistema' (most likely due to a circular import